function options = menuLib(steplog)

options = {};
switch steplog
    case 'a'
        fprintf(['Main menu:\n', ...
                 'c: Calibration          i: Idle \n', ...
                 'p: Position reading     r: Rotation \n', ...   
                 'm: Memorizing           t: PID tuning \n', ...
                 'd: Position control     f: Force control \n', ...
                 'q: Quit \n', ...
                 '1: Demo 1               2: Demo 2 \n', ...
                 '3: Demo 3               4: Demo 4 \n']);
        options = {'p', 't', 'q'};
    case 'q'
        fprintf(['Do not forget to rename the imported csv files \n' ...
                 '      before running this program again! \n', ...
                 '                   Goodbye! \n']);     
    % This is all about position reading             
    case 'ap'
        fprintf(['Which joint(s) are you going to read? \n' ...
                 '1: Joint 1     2: Joint 2       3: Both \n', ...
                 'r: Return      a: Main menu     q: Quit \n']);          
        options = {'1', 'r', 'a', 'q'};               
             
                         
    % This is all about PID control
    case 'at'
        fprintf(['Which joint(s) are you going to control? \n' ...
                 '1: Joint 1     2: Joint 2       3: Both \n', ...
                 'r: Return      a: Main menu     q: Quit \n']);          
        options = {'1', 'r', 'a', 'q'};  
    case 'at1'
        fprintf(['What trajectory will be used? \n' ...
                 'd: Default (f(t)=eta(1) rad) \n', ...
                 'c: Costumed (referring to desirePIDtrajectory(t)) \n', ...
                 'r: Return      a: Main menu     q: Quit \n']);          
        options = {'d', 'r', 'a', 'q'};
    case 'at1d'
        fprintf(['Enter the PID control gain as "[Kp, Ki, Kd]" \n' ...
                 'o: Parameters of last time \n', ...
                 'r: Return      a: Main menu     q: Quit \n']);   
        options = {-1};
    case 'at1dX'
        fprintf(['Begin to run? y/n \n' ...
                 'r: Return      a: Main menu     q: Quit \n']);   
        options = {'y', 'r', 'a', 'q'};
    case 'at1dXy'
        fprintf(['Plot and save? y/n \n' ...
                 'r: Return      a: Main menu     q: Quit \n']);   
        options = {'y', 'n', 'r', 'a', 'q'};
    case {'at1dXyy', 'at1dXyn'}
        fprintf(['Try other parameters? y/n \n' ...
                 'a: Main menu     q: Quit \n']);   
        options = {'y', 'n', 'r', 'a', 'q'};
end
end
%disp('System has been reset!')